### ISSUE TITLE
What if the sensor is connected over GPIO?

### ISSUE THREAD

**Issue by kauevestena** [mdrwiega/bosh_imu_driver#6]
I have the BNO055 in the adafruit breakout board, like this tutorial: https://learn.adafruit.com/bno055-absolute-orientation-sensor-with-raspberry-pi-and-beaglebone-black/software

can I simply swap the parameter "port" from '/dev/ttyUSB0' to '/dev/ttyAMA0' ?

thank you in advance.

**Comment by gpicardi** [comment]
Hi! I am currently in the same situation as you. Did you solve it?
Many thanks in advance

**Comment by kauevestena** [comment]
Hello!

At the present moment, i am using this driver: https://github.com/markusgrotz/ros_bno055_driver , 
Wich just makes use of the official Adafruit driver for python (need to be previously installed): https://github.com/adafruit/Adafruit_Python_BNO055

Are you also using a Raspberry Pi 3?
