### ISSUE TITLE
Node closes by itself

### ISSUE THREAD

**Issue by matteopantano** [mdrwiega/bosh_imu_driver#9]
To whom it may concern,

I am able to launch the node but immediately after it tells that the process closes by itself. Any idea of the issue?

```
started core service [/rosout]
process[bosch_imu_node-2]: started with pid [1780]
process[base_link_to_imu_bosch-3]: started with pid [1787]
[INFO] [1562490853.003331]: Opening serial port: /dev/ttyACM0...
[bosch_imu_node-2] process has finished cleanly
log file: /home/rovitis40/.ros/log/9539889e-a097-11e9-997f-2c9464017b87/bosch_imu_node-2*.log
```

**Comment by cvielma24** [comment]
Add print statements to show if serial device opened successfully or not. Could be a serial device config issue. Make sure you also have rospy.spin in your code.
